name: Nanoc

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.6", "2.7", "3.0", "3.1", "3.2", "3.3", "3.4"]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: bundler-b-${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('Gemfile') }}

      - run: |
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs "$(nproc)"

      - name: test_style
        if: ${{ matrix.ruby-version == '3.1' }}
        run: bundle exec rake test_style

      - name: test_unit
        run: bundle exec rake test_unit
        timeout-minutes: 3
